quietly set ACTELLIBNAME PolarFire
quietly set PROJECT_DIR "C:/Users/YanGao/Desktop/Yan/Test_ram_write"

if {[file exists presynth/_info]} {
   echo "INFO: Simulation library presynth already exists"
} else {
   file delete -force presynth 
   vlib presynth
}
vmap presynth presynth
vmap PolarFire "C:/Microchip/Libero_SoC_v2023.2/Designer/lib/modelsimpro/precompiled/vlog/polarfire"
if {[file exists COREFIFO_LIB/_info]} {
   echo "INFO: Simulation library COREFIFO_LIB already exists"
} else {
   file delete -force COREFIFO_LIB 
   vlib COREFIFO_LIB
}
vmap COREFIFO_LIB "COREFIFO_LIB"
if {[file exists COREAXI4SRAM_LIB/_info]} {
   echo "INFO: Simulation library COREAXI4SRAM_LIB already exists"
} else {
   file delete -force COREAXI4SRAM_LIB 
   vlib COREAXI4SRAM_LIB
}
vmap COREAXI4SRAM_LIB "COREAXI4SRAM_LIB"

vcom -2008 -explicit  -work presynth "${PROJECT_DIR}/hdl/logictest.vhd"
vcom -2008 -explicit  -work COREFIFO_LIB "${PROJECT_DIR}/component/Actel/DirectCore/COREFIFO/3.0.101/rtl/vhdl/core/fifo_pkg.vhd"
vcom -2008 -explicit  -work COREAXI4SRAM_LIB "${PROJECT_DIR}/component/work/COREAXI4SRAM_C1/COREAXI4SRAM_C1_0/rtl/vhdl/core/misc_pkg.vhd"
vcom -2008 -explicit  -work COREAXI4SRAM_LIB "${PROJECT_DIR}/component/work/COREAXI4SRAM_C1/COREAXI4SRAM_C1_0/rtl/vhdl/core/XHDL_misc.vhd"
vcom -2008 -explicit  -work COREAXI4SRAM_LIB "${PROJECT_DIR}/component/work/COREAXI4SRAM_C1/COREAXI4SRAM_C1_0/rtl/vhdl/core/XHDL_std_logic.vhd"
vcom -2008 -explicit  -work COREAXI4SRAM_LIB "${PROJECT_DIR}/component/work/COREAXI4SRAM_C2/COREAXI4SRAM_C2_0/rtl/vhdl/core/misc_pkg.vhd"
vcom -2008 -explicit  -work COREAXI4SRAM_LIB "${PROJECT_DIR}/component/work/COREAXI4SRAM_C2/COREAXI4SRAM_C2_0/rtl/vhdl/core/XHDL_misc.vhd"
vcom -2008 -explicit  -work COREAXI4SRAM_LIB "${PROJECT_DIR}/component/work/COREAXI4SRAM_C2/COREAXI4SRAM_C2_0/rtl/vhdl/core/XHDL_std_logic.vhd"
vcom -2008 -explicit  -work presynth "${PROJECT_DIR}/component/Actel/Simulation/CLK_GEN/1.0.1/CLK_GEN.vhd"
vcom -2008 -explicit  -work presynth "${PROJECT_DIR}/component/work/CLK_GEN_C0/CLK_GEN_C0.vhd"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/ResetSycnc.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/MasterAddressDecoder.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/DependenceChecker.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/BitScan0.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/TransactionController.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/MasterControl.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/RoundRobinArb.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/TargetMuxController.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/AddressController.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/Revision.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/DERR_Slave.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/DualPort_FF_SyncWr_SyncRd.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/DualPort_Ram_SyncWr_SyncRd.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/RdFifoDualPort.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/ReadDataMux.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/RequestQual.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/ReadDataController.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/RDataController.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/SlaveDataMuxController.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/RespController.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/FifoDualPort.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/WriteDataMux.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/WDataController.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4CrossBar/Axi4CrossBar.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/AHBL_Ctrl.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/AXI4_Read_Ctrl.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/AXI4_Write_Ctrl.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/AHB_SM.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/MstrAHBtoAXI4Converter.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/Bin2Gray.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/CDC_grayCodeCounter.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/CDC_rdCtrl.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/CDC_wrCtrl.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/RAM_BLOCK.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/CDC_FIFO.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/MstrClockDomainCrossing.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_DownConv_CmdFifoWriteCtrl.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/Hold_Reg_Ctrl.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_DownConv_Hold_Reg_Rd.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_DownConv_preCalcCmdFifoWrCtrl.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_DownConv_widthConvrd.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/FIFO_CTRL.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/FIFO.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/byte2bit.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_DownConv_readWidthConv.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_DownConv_Hold_Reg_Wr.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_DownConv_widthConvwr.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_brespCtrl.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_DownConv_writeWidthConv.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DownConverter.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_AChannel.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_BChannel.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_RChannel_SlvRid_Arb.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_RChan_Ctrl.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_preCalcRChan_Ctrl.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/FIFO_downsizing.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_RChannel.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_WChan_Hold_Reg.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_WChan_ReadDataFifoCtrl.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_Wchan_WriteDataFifoCtrl.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/FIFO_upsizing.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_WChannel.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/DWC_UpConv_preCalcAChannel.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/UpConverter.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/MstrDataWidthConv.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/MstrProtocolConverter.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/RegSliceFull.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/RegisterSlice.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/MasterConvertor.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/SlvClockDomainCrossing.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/SlvDataWidthConverter.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/SlvAxi4ProtConvRead.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/SlvAxi4ProtConvWrite.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/SlvAxi4ProtocolConv.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/SlvAxi4ProtConvAXI4ID.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/SlvProtocolConverter.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/Axi4Convertors/SlaveConvertor.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREAXI4INTERCONNECT/2.8.103/rtl/vlog/core/CoreAxi4Interconnect.v"
vlog -sv -work presynth "${PROJECT_DIR}/component/work/COREAXI4INTERCONNECT_C0/COREAXI4INTERCONNECT_C0.v"
vcom -2008 -explicit  -work presynth "${PROJECT_DIR}/component/work/COREAXI4SRAM_C2/COREAXI4SRAM_C2_0/rtl/vhdl/test/user/misc_pkg.vhd"
vcom -2008 -explicit  -work presynth "${PROJECT_DIR}/component/work/COREFIFO_C0/COREFIFO_C0_0/rtl/vhdl/test/user/XHDL_std_logic.vhd"
vcom -2008 -explicit  -work COREAXI4SRAM_LIB "${PROJECT_DIR}/component/work/COREAXI4SRAM_C2/COREAXI4SRAM_C2_0/rtl/vhdl/core/CoreAXI4SRAM_MAINCTRL.vhd"
vcom -2008 -explicit  -work COREAXI4SRAM_LIB "${PROJECT_DIR}/component/work/COREAXI4SRAM_C2/COREAXI4SRAM_C2_0/rtl/vhdl/core/CoreAXI4SRAM_MEMIF.vhd"
vcom -2008 -explicit  -work COREAXI4SRAM_LIB "${PROJECT_DIR}/component/work/COREAXI4SRAM_C2/COREAXI4SRAM_C2_0/rtl/vhdl/core/CoreAXI4SRAM_SLVIF.vhd"
vcom -2008 -explicit  -work COREAXI4SRAM_LIB "${PROJECT_DIR}/component/work/COREAXI4SRAM_C2/COREAXI4SRAM_C2_0/rtl/vhdl/core/CoreAXI4SRAM.vhd"
vcom -2008 -explicit  -work presynth "${PROJECT_DIR}/component/work/COREAXI4SRAM_C2/COREAXI4SRAM_C2.vhd"
vcom -2008 -explicit  -work presynth "${PROJECT_DIR}/component/Actel/Simulation/RESET_GEN/1.0.1/RESET_GEN.vhd"
vcom -2008 -explicit  -work presynth "${PROJECT_DIR}/component/work/RESET_GEN_C1/RESET_GEN_C1.vhd"
vcom -2008 -explicit  -work presynth "${PROJECT_DIR}/hdl/axi_master_florian_64bits.vhd"
vcom -2008 -explicit  -work presynth "${PROJECT_DIR}/component/work/tb_axi_florian_64bits/tb_axi_florian_64bits.vhd"

vsim -L PolarFire -L presynth -L COREFIFO_LIB -L COREAXI4SRAM_LIB  -t 1ps -pli C:/Microchip/Libero_SoC_v2023.2/Designer/lib/modelsimpro/pli/pf_crypto_win_me_pli.dll presynth.tb_axi_florian_64bits
add wave /tb_axi_florian_64bits/*
run 1000ns
